agent-token-secret: my-kubernetes-secret
debug: true
image: my.registry.dev/buildkite-agent:latest
job-ttl: 5m
image-pull-backoff-grace-period: 60s
poll-interval: 5s
max-in-flight: 100
namespace: my-buildkite-ns
org: my-buildkite-org

# only set cluster-uuid if the pipelines are in a cluster
# the UUID may be found in the cluster settings
cluster-uuid: beefcafe-abbe-baba-abba-deedcedecade

tags:
  - queue=my-queue
  - priority=high

# Causes the controller to prohibit the kubernetes plugin specified within jobs
# (pipeline YAML) - enabling this causes jobs with a kubernetes plugin to fail,
# preventing the pipeline YAML from having any influence over the podSpec
prohibit-kubernetes-plugin: true

# Applies to the checkout container in all spawned pods
default-checkout-params:
  gitCredentialsSecret:
    secretName: "my-git-credentials"
  envFrom:
    - prefix: GITHUB_
      secretRef:
        name: github-secrets

# Applies to all command containers in all spawned pods
default-command-params:
  interposer: vector
  envFrom:
    - prefix: DEPLOY_
      secretRef:
        name: deploy-secrets

# Applies to all sidecar containers in all spawned pods
default-sidecar-params:
  envFrom:
    - prefix: LOGGING_
      configMapRef:
        name: logging-config

# This will be applied to the job's podSpec as a strategic merge patch
# See https://kubernetes.io/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch
pod-spec-patch:
  serviceAccountName: buildkite-agent-sa
  automountServiceAccountToken: true
  containers:
    - name: container-0
      env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-secrets
              key: github-token
      resources:
        requests:
          cpu: 1000m # one core
          mem: 4Gi
